### PR TITLE
Ternary mistake fix

### LINKED ISSUE #4: Can't decompile scripts due to incorrect detection of ternary operator
For a list of failing scripts (mostly vanilla):
https://github.com/rotators/ReDefine.Examples/tree/master/Games/Fallout2.Steam/Errors

Code that triggers the issue:

```
procedure start begin
    critter_add_trait(self_obj, 1, 5, 8);
    if ((cur_map_index == 26) or (cur_map_index == 25)) then begin
        critter_add_trait(self_obj, 1, 6, 2);
    end
    else begin
        critter_add_trait(self_obj, 1, 6, 21);
    end
end
```

Basically this happens because of how ternary operator `x if y else z` works: it has exactly the same opcodes as IF operator, with the exception that it always has both branches (then and else) and both branches must leave 1 value in the stack (expressions).
In some old compiler `critter_add_trait` was erroneously set as a statement (no return value), while in reality (Fallout 2 v1.02d) it always returns -1. So the newer compiler will add `O_POP` after every call (if value was not used).

Because this call is the last one in both branches, it looks like a ternary operator from decompiler point of view. It seems to be impossible to distinguish between them.

If you disable the support of ternary operator altogether (buy commenting out relevant code in `BuildTreeBranch()`), the script will decompile, but with a warning about data left in stack (which won't necessarily break the game). So we must support the same behavior, so all vanilla scripts can be decompiled without error.

One possible solution is to add a command line arg that denotes the script as vanilla-compiled or "legacy" script, and disable trying to parse all new sfall syntax.

### PR DESCRIPTION
**Pull request by phobos2077**
Handle cases where if/else block with single exprstatement was incorrectly identified as ternary operator (closes #4)

### CODE REVIEW

File: FalloutScriptDecompile.cpp [hunk 1]
```diff
@@ -539,22 +539,25 @@ uint32_t CFalloutScript::BuildTreeBranch(CNodeArray& NodeArray, uint32_t nStartI
...
+            CNode& jumpNode = NodeArray[ulElseIndex - 1];
+            if (jumpNode.m_Opcode.GetOperator() == COpcode::O_JMP)
             {
-                uint32_t ulSkipOffset = NodeArray[ulElseIndex - 1].m_Opcode.GetArgument();
+                uint32_t ulSkipOffset = jumpNode.m_Opcode.GetArgument();
                 if (ulSkipOffset > NodeArray[j].m_ulOffset)
                 {
                     ulSkipIndex = BuildTreeBranch(NodeArray, ulElseIndex, ulSkipOffset); // false branch
-                    if (NodeArray[ulElseIndex - 2].IsExpression() && NodeArray[ulSkipIndex - 1].IsExpression())
+                    if (ulElseIndex == j + 3 && ulSkipIndex == ulElseIndex + 1 &&
```
Comment (wipe2238) [inline FalloutScriptDecompile.cpp:553]: `FalloutScriptDecompile.cpp:553:37: warning: comparison of integer expressions of different signedness: ‘int32_t’ {aka ‘int’} and ‘uint32_t’ {aka ‘unsigned int’} [-Wsign-compare]`

Comment (phobos2077) [reply FalloutScriptDecompile.cpp:553]: Interesting why VS doesn't produce the same warning.
